version: '2'

services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # Configuration
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      # Fichiers servis
      - ./nginx/html:/usr/share/nginx/html
      # SSL - Modifier HOSTNAME en fonction de l'emplacement des certificats LetsEncrypt
      - /etc/letsencrypt/live/HOSTNAME/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/HOSTNAME/privkey.pem:/certs/privkey.pem:ro
    networks:
      - wwwnet

  php:
    image: php:8-fpm
    container_name: php8-fpm
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - wwwnet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MOT_DE_PASSE
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - wwwnet

networks:
    wwwnet:
        driver: bridge